### ISSUE TITLE
Extension removed?

### ISSUE THREAD

**Issue by RIAEvangelist** [ktty1220/export-cookie-for-puppeteer#1]
Looks like the extension may have been removed from googles store?

**Comment by ktty1220** [comment]
Yes. It was removed from the Web Store the other day.

However, I don't know the reason why it was removed, so I am having trouble dealing with it.

Unfortunately, there is a possibility that it will not be restored.:cry:

**Comment by RIAEvangelist** [comment]
Is your account deactivated, or could you still upload it under another name? Maybe with a new icon and description as well, just in case you matched some algorithm flag.

**Comment by ktty1220** [comment]
Thanks for the suggestion.

I'll try to solve the problem using the regular method first, and if that doesn't solve, I'll consider that method.
